In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [132]:
import warnings
warnings.filterwarnings('ignore')

In [133]:
df=sns.load_dataset('tips')

In [134]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [135]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [136]:
#predict whats the time? if its luanch or dinner>> time us target

In [137]:
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [138]:
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [139]:
#EDA > sunjective
#encoding , missing value treatment , scaling >> automate

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [141]:
#science time is a nominal variable , we will use label encoder
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [142]:
df['time']=encoder.fit_transform(df['time'])

In [143]:
df.time.unique() #dinner -1 #luanch - 0

array([0, 1])

In [144]:
x=df.drop('time',axis=1)

In [145]:
y=df['time']

In [146]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.2)

In [147]:
#handling the missing value
#data encoding
#feature scaling

In [148]:
from sklearn.impute import SimpleImputer # for missing value

In [149]:
from sklearn.preprocessing import OneHotEncoder # for encoding

In [150]:
from sklearn.preprocessing import StandardScaler # for scaling

In [151]:
from sklearn.pipeline import Pipeline # a seq of data transformer # step by step missing value , encoding .... kadega
from sklearn.compose import ColumnTransformer# grp each pipeline steps on each columns

In [152]:
cat_cols=['sex','smoker','day']
num_cols=['total_bill','tip','size']

In [153]:
#feature engineering automationusing pipeline and columntransformer
num_pipeline=Pipeline(steps=[('imputation',SimpleImputer(strategy='median')),('scaling',StandardScaler())])

In [154]:
cat_pipeline=Pipeline(steps=[('imputation',SimpleImputer(strategy='most_frequent')),('encoding',OneHotEncoder())])

In [155]:
preProcessor=ColumnTransformer([("num_pipeline",num_pipeline,num_cols),('cat_pipelines',cat_pipeline,cat_cols)])

In [156]:
x_train=preProcessor.fit_transform(x_train)
x_test=preProcessor.transform(x_test)

In [157]:
x_train

array([[-0.28611937, -1.47443803, -0.57766863, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.02695905, -0.71612531,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.3716196 ,  1.19880579,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.23206267,  0.43283335, -0.57766863, ...,  0.        ,
         0.        ,  1.        ],
       [-1.06543688, -1.29060464, -0.57766863, ...,  1.        ,
         0.        ,  0.        ],
       [-0.29287646,  0.1034652 ,  0.44638031, ...,  1.        ,
         0.        ,  0.        ]])

In [158]:
x_test

array([[-1.85376383, -1.48209775, -1.60171757,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.08453291,  0.04984713, -0.57766863,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.79501474,  0.36389583,  0.44638031,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.59356688, -0.33313909, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.18349826,  0.04984713, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-1.32783714, -1.14506988, -0.57766863,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.   

In [159]:
## eg
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [160]:
models={"support vector classifier": SVC(),"DT classifier": DecisionTreeClassifier(),"Logistic regression":LogisticRegression()}

In [161]:
from sklearn.metrics import accuracy_score

def model_train_eval(x_train, y_train, x_test, y_test, models):
    evaluation = {}
    for i in range(len(models)):
        model = list(models.values())[i]
        model.fit(x_train, y_train)
        y_pred = model.predict(x_test)
        model_score = accuracy_score(y_test, y_pred)
        evaluation[list(models.keys())[i]] = model_score
    return evaluation


In [162]:
model_train_eval(x_train,y_train,x_test,y_test,models)

{'support vector classifier': 0.9183673469387755,
 'DT classifier': 0.8979591836734694,
 'Logistic regression': 0.9183673469387755}

In [200]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [202]:
rf

RandomForestClassifier()

In [204]:
#hyperparameter tuning
from sklearn.model_selection import RandomizedSearchCV
params={
    'max_depth':[1,2,3,5,10,None],
    'n_estimators':[50,100,200,300],
    'criterion':['gini','entropy']
}

In [206]:
params

{'max_depth': [1, 2, 3, 5, 10, None],
 'n_estimators': [50, 100, 200, 300],
 'criterion': ['gini', 'entropy']}

In [208]:
clf=RandomizedSearchCV(rf,param_distributions=params,cv=5,verbose=3,scoring='accuracy')

In [210]:
clf.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.923 total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.949 total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, n_estimators=300;, score=1.000 total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.974 total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, n_estimators=300;, score=0.974 total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, n_estimators=200;, score=0.923 total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, n_estimators=200;, score=0.949 total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, n_estimators=200;, score=1.000 total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=10, n_estimators=200;, score=0.974 total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=10, n_estimators=200;, score=0.974 total time=   0.2s

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 2, 3, 5, 10, None],
                                        'n_estimators': [50, 100, 200, 300]},
                   scoring='accuracy', verbose=3)

In [212]:
clf.best_params_

{'n_estimators': 200, 'max_depth': 3, 'criterion': 'gini'}

In [218]:
clf.best_score_

0.9794871794871796

In [220]:
#to do
#use total_bill as target variable and make it a regressor problem 
#automate the , training,testing and also random gorest regresor with MLR, SVR models